### ISSUE TITLE
Evaluate the status of lookout-flake8-analyzer

### ISSUE THREAD

**Issue by smola** [src-d/lookout-flake8-analyzer#2]
- What is the status of this analyzer?
- Does it work with latest lookout?
- What's missing for deployment (e.g. CI, config, published Docker image)?

**Comment by carlosms** [comment]
I've done a quick test building the image locally
```
make docker-build
docker run --net=host srcd/lookout-flake8-analyzer:dev-242406f-dirty
```

Running with `lookout-sdk` from master (9d64baf), it produces comments as expected
```
[2019-03-12T10:39:11.992237721Z]  INFO line comment app=lookout-sdk file=hello.py line=1 text=E201: whitespace after '('
[2019-03-12T10:39:11.992268052Z]  INFO line comment app=lookout-sdk file=hello.py line=1 text=E202: whitespace before ')'
```

What it needs before it can be deployed:
- Create a chart, similar to the [gometalint](https://github.com/src-d/charts/tree/master/lookout-gometalint-analyzer) one.
- Enable it in travis. This includes config for github releases (GITHUB_TOKEN), docker hub (DOCKER_USERNAME _PASSWORD), and a few other vars for the helm deployment.
- Publish a release. To do this we need to add permissions for Apps team to this repo.

**Comment by smacker** [comment]
I would also update sdk & grpc versions in it before deployment.

There are known issues in old version which would cause problems for the analyzer on staging/production. (to be more precise https://github.com/grpc/grpc/issues/14088 and another one when client re-connects successfully only after the second try)

**Comment by se7entyse7en** [comment]
With the updated python sdk we will also have better logs on lookout side.

**Comment by carlosms** [comment]
Can we close this one @smola?
